import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import Navbar from "@/components/Navbar";

const poppins = Poppins({ subsets: ["latin"], weight: ['300', '400', '500'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={poppins.className}>
          <div className=" mx-auto max-w-screen-lg h-screen flex flex-col">
            <Navbar />
            <div className=" flex-grow">
            {children}
            </div>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
